packages:
  - packages/*
  - apps/*

configDependencies:
  '@pnpm/plugin-types-fixer': 0.1.0+sha512-bLww63gRHi7siYTqFJb5qNdcXadU0jv20Et6z5AryMZ7FlLolbEJOrXLpg8+amQZNHHNW1dfFUBGVw/9ezQbFg==

onlyBuiltDependencies:
  - '@swc/core'
  - bigint-buffer
  - bufferutil
  - esbuild
  - keccak
  - msw
  - secp256k1
  - sharp
  - utf-8-validate
  - workerd
