/**
 * Shared environment setup for SATI examples.
 *
 * Loads the FIRST .env file found in this order:
 * 1. examples/.env
 * 2. repo root .env
 *
 * Exports helpers for creating a Solana signer from a keypair JSON file.
 *
 * Required env vars:
 *   KEYPAIR_PATH - path to Solana keypair JSON (e.g. ~/.config/solana/id.json)
 *
 * Optional env vars:
 *   RPC_URL    - Solana RPC endpoint (defaults to network default)
 *   PINATA_JWT - for IPFS uploads (not needed if using hosted uploader)
 *   NETWORK    - mainnet | devnet | localnet (default: devnet)
 *   AGENT_MINT - existing agent mint address for feedback examples
 *   AGENT_ID   - existing agent ID in CAIP-2 format (for agent0-sdk examples)
 */

import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { fileURLToPath } from "node:url";
import dotenv from "dotenv";
import { createKeyPairSignerFromBytes, type KeyPairSigner } from "@solana/kit";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const candidates = [path.join(__dirname, "..", ".env"), path.resolve(__dirname, "../..", ".env")];

for (const p of candidates) {
  try {
    if (fs.existsSync(p) && fs.statSync(p).isFile()) {
      dotenv.config({ path: p });
      break;
    }
  } catch {
    // ignore and continue
  }
}

function expandHome(p: string): string {
  if (p.startsWith("~/")) return path.join(os.homedir(), p.slice(2));
  return p;
}

export const RPC_URL = process.env.RPC_URL;
export const PINATA_JWT = process.env.PINATA_JWT;
export const NETWORK = (process.env.NETWORK ?? "devnet") as "mainnet" | "devnet" | "localnet";

/** Agent mint address (base58) for sati-sdk examples. */
export const AGENT_MINT = process.env.AGENT_MINT;

/** Agent ID in CAIP-2 format (solana:<chainRef>:<mint>) for agent0-sdk examples. */
export const AGENT_ID = process.env.AGENT_ID;

/**
 * Load a KeyPairSigner from a Solana keypair JSON file.
 *
 * Uses KEYPAIR_PATH env var, or pass an explicit path.
 * Keypair JSON files are generated by `solana-keygen new`.
 */
export async function loadSigner(keypairPath?: string): Promise<KeyPairSigner> {
  const resolvedPath = keypairPath ?? process.env.KEYPAIR_PATH;
  if (!resolvedPath || resolvedPath.trim() === "") {
    throw new Error("KEYPAIR_PATH env var or keypairPath argument is required");
  }
  const expanded = expandHome(resolvedPath);
  const data = fs.readFileSync(expanded, "utf-8");
  const secretKey = Uint8Array.from(JSON.parse(data));
  return createKeyPairSignerFromBytes(secretKey);
}
